version: "3.1"

services:

  notes-app-server:
    image: node:20-alpine
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://user:password@db:5432/notes
    working_dir: /app
    volumes:
      - ./notes-app-server:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: npm run start:migrate

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: secret-user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pg_data:
